#!/bin/bash

### BEGIN INIT INFO
# Provides:          varnishsentry
# Required-Start:    $network $local_fs
# Required-Stop:     $network $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: varnishsentry daemon
### END INIT INFO

VARNISHSENTRY_VIRTUALENV=""
VARNISHSENTRY_CONFIG="/etc/varnishsentry.conf"

varnishsentry_start () {
    varnishsentry start \
        --daemon \
        --config="$VARNISHSENTRY_CONFIG"
}

varnishsentry_stop () {
    varnishsentry stop \
        --config="$VARNISHSENTRY_CONFIG"
}

varnishsentry_restart () {
    varnishsentry_stop
    varnishsentry_start
}

varnishsentry_status () {
    varnishsentry status \
        --config="$VARNISHSENTRY_CONFIG"
}

if [ -n "$VARNISHSENTRY_VIRTUALENV" ]; then
    source "$VARNISHSENTRY_VIRTUALENV/bin/activate"
fi

case "$1" in
    start)
        varnishsentry_start
    ;;

    stop)
        varnishsentry_stop
    ;;

    restart)
        varnishsentry_restart
    ;;

    status)
        varnishsentry_status
    ;;

    reload|force-reload)
        echo "Use restart." 1>&2
        exit 1
    ;;

    *)
        echo "Usage: $0 {start|stop|restart|status}" 1>&2
        exit 64  # EX_USAGE
    ;;
esac

if [ -n "$VARNISHSENTRY_VIRTUALENV" ]; then
    deactivate
fi

exit 0
